version: "3.1"
services:
  spark:
    image: jakkie555/spark
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - ./work:/home/jakkie/work
    tty: 
        true

  mysql:
    image: jakkie555/mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "stackoverflow"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
