version: '3.1'
services:
    spark:
        image: jupyter/pyspark-notebook
        ports:
            - 8888:8888
            - 4040:4040
        volumes:
            - ./work:/home/jovyan/work
        networks:
            - spark-network
    
    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        expose:
            - "3306"
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: 'stackoverflow'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        networks:
            - spark-network
networks:
    spark-network:
        driver: bridge